---
- name: Setting host facts using complex arguments
  set_fact:
    gitlab_baseurl_api: "{{ gitlab_url }}{{ gitlab_api_context_path }}"

- name: Add variables to gitlab instance
  include_tasks: instance-variables.yaml
  when: enabled_gitlab_config_variables_instance